import telebot
from telebot.types import
token="8525363907:AAFb3kZ2d6kXjakZi_atGCixoqHbmibcmB8"
bot=telebot.TeleBot (token)
@bot.message_handler(commands=[' start'])
def send (message) :
    markup=InlineKeyboardMarkup()
    about_button= InlineKeyboardButton("Ø®ØµÙ… 4 Ù‚Ù†ÙˆØ§Øª Ù…Ù…Ø§Ø±Ø³Ø§Øª ÙØ®Ù…ÙŠÙ† Ø¨Ø§Ù„ÙÙŠØ³Ø§ØªğŸ¥µğŸ”¥1ï¸âƒ£ Ù…Ù…Ø§Ø±Ø³Ø§Øª Ù…Ø´Ø§Ù‡ÙŠØ± ØªÙˆÙŠØªØ± Ø¨Ø§Ù„ÙÙŠØ³Ø§Øª 7000ÙÙŠØ¯ÙŠÙˆ â€2ï¸âƒ£ Ù‚Ù†Ø§Ù‡ Ø­ØµØ±ÙŠØ§Øª ÙØ®Ù…ÙŠÙ† Ø¨Ø§Ù„ÙÙŠØ³Ø§Øª 3500ÙÙŠØ¯ÙŠÙˆ 3ï¸âƒ£Ù‚Ù†Ø§Ù‡ Ù…Ù…Ø§Ø±Ø³Ø§Øª Ø¨Ø§Ù„ÙÙŠØ³Ø§Øª 2600ğŸ’¦4ï¸âƒ£Ù‚Ù†Ø§Ù‡ Ù…Ù…Ø§Ø±Ø³Ø§ØªÙŠ ÙˆØ®Ù†Ø§Ø«ÙŠğŸ¤¦ğŸ»â€â™‚ï¸",callback='about')
    button1=InlineKeyboardButton("Ù†Ø¨Ø°Ù‡ Ø¹Ù† Ø§Ù„Ù‚Ù†ÙˆØ§Øª",callback_data="clarification")
    markup.add (about_button,button1)
    bot.send_message(message.chat.id,"Ø§Ø®ØªØ± Ù…Ù† Ø§Ù„Ø®ÙŠØ§Ø±Ø§Øª Ø§Ù„ØªØ§Ù„ÙŠØ©",reply_markup=markup)
@bot.callback_query_handler(func=lambda call:True)
def call(call) :
    if call.data== "about":
        bot.send_photo(call.message.chat.id ,open=("pic/gay.jpg","rb"))
    elif call.data== "clarification":
        bot.send_(call.message.chat.id ,"Ù†Ø¨Ø°Ù‡ Ø¹Ù† Ø§Ù„Ù‚Ù†ÙˆØ§Øª")
print("Ø§Ù„Ø¨ÙˆØª Ø´ØºØ§Ù„")
bot.polling()
